const education = [
    'Bachelor of Medicine, Bachelor of Surgery (MBBS)',
    'Doctor of Medicine (MD)',
    'Master of Surgery (MS)',
    'Doctor of Osteopathic Medicine (DO)',
    'Doctor of Dental Medicine (DMD)',
    'Doctor of Pharmacy (PharmD)',
    'Doctor of Veterinary Medicine (DVM)',
    'Doctor of Physical Therapy (DPT)',
    'Doctor of Optometry (OD)',
    'Doctor of Podiatric Medicine (DPM)',
    'Doctor of Chiropractic (DC)',
    'Doctor of Naturopathic Medicine (ND)',
    'Doctor of Nursing Practice (DNP)',
    'Doctor of Psychology (PsyD)',
    'Doctor of Occupational Therapy (OTD)',
    'Doctor of Public Health (DrPH)',
    'Doctor of Health Administration (DHA)',
    'Doctor of Medical Science (DMSc)',
    'Doctor of Philosophy in Medicine (PhD)',
    'Doctor of Science in Medicine (DScMed)',
    'Doctor of Health Science (DHSc)',
    'Doctor of Surgical Science (DSurgSc)',
    'Doctor of Medical Education (DME)',
    'Doctor of Medical Physics (DMP)',
    'Doctor of Clinical Medicine (DClinMed)',
    'Doctor of Clinical Dentistry (DClinDent)',
    'Doctor of Medical Dentistry (DMDent)',
    'Doctor of Medicine by Research (MD(Res))',
    'Doctor of Biomedical Science (DBMS)',
    'Doctor of Health Professions Education (DHPE)',
    'Doctor of Medical Ultrasound (DMU)',
    'Doctor of Dental Surgery (DDS)',
    'Doctor of Science in Dentistry (DScD)',
    'Doctor of Podiatric Surgery (DPodS)',
    'Doctor of Science in Podiatry (DScPod)',
    'Doctor of Health Science in Podiatry (DHScPod)',
    'Doctor of Podiatric Medicine (DPodM)'
    // Feel free to add more degrees as required
  ];
  
  export default education;