const specialties = [
    "Dermatologist",
    "Pediatrician",
    "Cardiologist",
    "Oncologist",
    "Neurologist",
    "Psychiatrist",
    "Orthopedist",
    "Endocrinologist",
    "Gynecologist",
    "Allergist",
    "Ophthalmologist",
    "Rheumatologist",
    "Surgeon",
    "Pulmonologist",
    "Gastroenterologist",
    "Nephrologist",
    "Otolaryngologist",
    "Neonatologist",
    "Anesthesiologist",
    "Radiologist",
    "Internist",
    "Physiatrist",
    "Infectious Disease Specialist",
    "Geriatrician",
    "Hepatologist",
    // Add more specialties as needed
  ];
  
  export default specialties;